---
resource_types:
- name: bbl-state-resource
  type: docker-image
  source:
    repository: cfinfrastructure/bbl-state-resource
- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource
- name: concourse-pipeline
  type: docker-image
  source:
    repository: concourse/concourse-pipeline-resource
    tag: 3
- name: google-cloud-storage
  type: docker-image
  source:
    repository: frodenas/gcs-resource
    tag: "v0.3.0"
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

resources:
- name: bbl-state
  type: git
  source:
    branch: master
    uri: ((bbl_state.url))
    username: ((git-credentials.username))
    password: ((git-credentials.password))
- name: bosh-deployment
  type: bosh-deployment
- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git
    tag_filter: ((resource_version_cf-deployment-concourse-tasks.ref))
- name: concourse-tasks
  type: git
  source:
    branch: master
    uri: ((finkit-concourse-tasks.uri))
    private_key: ((finkit-concourse-tasks.key))
- name: sonarqube-boshrelease
  type: git
  source:
      uri: git@github.com:finkit/sonarqube-boshrelease
      branch: master
      private_key: ((sonarqube_boshrelease_github_deploy_key.private))
- name: devtools-tests
  type: git
  source:
      uri: git@github.com:finkit/devtools-tests
      branch: master
      private_key: ((github-devtools-tests-key.private))
- name: dev-sonarqube-boshrelease-tarball
  type: google-cloud-storage
  source:
    bucket: ((buildtools-release-tarballs.bucket))
    json_key: ((prod-build-storage-google-key))
    versioned_file: sonarqube-boshrelease/dev-release.tgz
- name: final-sonarqube-boshrelease-tarball
  type: google-cloud-storage
  source:
    bucket: ((buildtools-release-tarballs.bucket))
    json_key: ((prod-build-storage-google-key))
    regexp: sonarqube-boshrelease/sonarqube-boshrelease-v(.*).tgz
- name: warden-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
- name: github-prerelease
  type: github-release
  source:
    <<: &github-release-source
      owner: finkit
      repository: sonarqube-boshrelease
      access_token: ((github-access-token))
    # "pre_release: true" is not effective on it's own, "release: false" must also be set
    # https://github.com/concourse/github-release-resource/issues/40
    pre_release: true
    release: false
- name: github-release
  type: github-release
  source:
    <<: *github-release-source
    # drafts: true
- name: read-snapshot-versions
  type: git
  source:
    private_key: ((buildstack-pipeline-versions.key))
    uri: ((buildstack-pipeline-versions.uri))
    paths:
    - initial-versions.yml
- name: set-pipeline
  type: concourse-pipeline
  source:
    target: ((concourse-auth.target))
    teams:
    - name: ((concourse-auth.team))
      username: ((concourse-auth.username))
      password: ((concourse-auth.password))
- name: slack-alert
  type: slack-notification
  source:
    url: ((slack.hook))
- name: version
  type: semver
  source:
    driver: gcs
    bucket: ((buildtools-release-tarballs.bucket))
    json_key: ((prod-build-storage-google-key))
    initial_version: 0.0.0
    key: sonarqube.version

groups:
- name: release
  jobs:
  - set-pipeline
  - create-dev-release
  - test-sonarqube
  - release-final
  - prerelease-major
  - prerelease-minor
  - prerelease-patch
- name: destroy
  jobs:
  - destroy-infrastructure

jobs:
- name: set-pipeline
  plan:
  - get: read-snapshot-versions
  - get: sonarqube-boshrelease
    trigger: true
  - put: set-pipeline
    params:
      pipelines:
      - name: sonarqube-boshrelease
        team: ((concourse-auth.team))
        config_file: sonarqube-boshrelease/ci/pipeline.yml
        vars_files:
        - read-snapshot-versions/initial-versions.yml
  <<: &slack-alert
    on_failure:
      put: slack-alert
      params:
        channel: ((slack.channel))
        username: ((slack.user))
        text: "<((concourse-auth.target))/teams/((concourse-auth.team))/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}|${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}>: ${BUILD_ID} - [Failed]"
        icon_emoji: ":fire:"

- name: create-dev-release
  plan:
  - aggregate:
    - get: sonarqube-boshrelease
      passed:
      - set-pipeline
      trigger: true
  - task: create-release
    file: sonarqube-boshrelease/ci/tasks/create-dev-release.yml
  - put: dev-sonarqube-boshrelease-tarball
    params: { file: dev-sonarqube-boshrelease-tarball/dev-release.tgz }
  <<: *slack-alert

- name: test-sonarqube
  build_logs_to_retain: 20
  serial: true
  plan:
  - aggregate:
    - get: bbl-state
    - get: cf-deployment-concourse-tasks
      trigger: true
    - get: concourse-tasks
    - get: devtools-tests
    - get: dev-sonarqube-boshrelease-tarball
      passed: [create-dev-release]
      trigger: true
    - get: sonarqube-boshrelease
      passed: [create-dev-release]
    - get: warden-stemcell
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    input_mapping:
      bbl-config: sonarqube-boshrelease
      bbl-state: bbl-state
    output_mapping:
      updated-bbl-state: updated-bbl-state
    params:
      BBL_CONFIG_DIR: ci/customisations
      BBL_ENV_NAME: sonarqube-boshrelease
      BBL_GCP_REGION: ((gcp.region))
      BBL_GCP_SERVICE_ACCOUNT_KEY: ((gcp.key))
      BBL_IAAS: gcp
      SKIP_LB_CREATION: true
    ensure:
      put: bbl-state
      params:
        repository: updated-bbl-state
        rebase: true
  - task: create-sonarqube-bosh-config
    params:
      BOSH_DEPLOYMENT: &deployment-name sonarqube
    file: sonarqube-boshrelease/ci/tasks/create-bosh-config.yml
  - put: bosh-deployment
    params:
      source_file: source/source.yml
      manifest: sonarqube-boshrelease/sonarqube.yml
      ops_files:
      - sonarqube-boshrelease/operations/add-test-groups.yml
      - sonarqube-boshrelease/operations/add-test-users.yml
      - sonarqube-boshrelease/operations/sonar-local-auth.yml
      releases:
      - dev-sonarqube-boshrelease-tarball/dev-release.tgz
      stemcells:
      - warden-stemcell/stemcell.tgz
      vars:
        deployment_name: *deployment-name
  - task: test-sonarqube
    file: sonarqube-boshrelease/ci/tasks/test-sonarqube.yml
    params:
      BOSH_DEPLOYMENT: *deployment-name
    ensure:
      put: bosh-deployment
      params:
        source_file: source/source.yml
        delete:
          enabled: true
          force: true
        vars:
          deployment_name: *deployment-name
  - task: bbl-destroy
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    input_mapping:
      bbl-state: bbl-state
    output_mapping:
      updated-bbl-state: updated-bbl-state
    params:
      BBL_GCP_SERVICE_ACCOUNT_KEY: ((gcp.key))
    ensure:
      put: bbl-state
      params:
        repository: updated-bbl-state
        rebase: true
  <<: *slack-alert

- name: release-final
  serial_groups:
  - github-release
  plan:
  - put: version
    params:
      bump: final
  - do: &do-release
    - aggregate:
      - get: sonarqube-boshrelease
        passed: &tests
        - test-sonarqube
    - task: create-release
      file: sonarqube-boshrelease/ci/tasks/create-final-release.yml
    - put: final-sonarqube-boshrelease-tarball
      params: { file: final-sonarqube-boshrelease-tarball/sonarqube-boshrelease-v*.tgz }
    - put: github-release
      params: &put-github-release-params
        name: version/version
        tag: version/version
        tag_prefix: v
        globs:
        - final-sonarqube-boshrelease-tarball/*.tgz
  <<: *slack-alert

- name: prerelease-major
  serial_groups:
  - github-release
  plan:
  - put: version
    params:
      bump: major
      pre: rc
  - do: &do-prerelease
    - aggregate:
      - get: sonarqube-boshrelease
        passed: *tests
    - task: create-release
      file: sonarqube-boshrelease/ci/tasks/create-final-release.yml
    - put: github-prerelease
      params: *put-github-release-params
  <<: *slack-alert

- name: prerelease-minor
  serial_groups:
  - github-release
  plan:
  - put: version
    params:
      bump: minor
      pre: rc
  - do: *do-prerelease
  <<: *slack-alert

- name: prerelease-patch
  serial_groups:
  - github-release
  plan:
  - put: version
    params:
      bump: patch
      pre: rc
  - do:
    - aggregate:
      - get: sonarqube-boshrelease
        passed: *tests
        trigger: true
    - task: create-release
      file: sonarqube-boshrelease/ci/tasks/create-final-release.yml
    - put: github-prerelease
      params: &put-github-release-params
        name: version/version
        tag: version/version
        tag_prefix: v
        globs:
        - final-sonarqube-boshrelease-tarball/*.tgz
  <<: *slack-alert

- name: destroy-infrastructure
  plan:
  - get: bbl-state
  - get: cf-deployment-concourse-tasks
  - task: bbl-destroy
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    input_mapping:
      bbl-state: bbl-state
    output_mapping:
      updated-bbl-state: updated-bbl-state
    params:
      BBL_GCP_SERVICE_ACCOUNT_KEY: ((gcp.key))
    ensure:
      put: bbl-state
      params:
        repository: updated-bbl-state
        rebase: true
  <<: *slack-alert
